/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zxy_libjpegturbo_JpegTurboCompressor */

#ifndef _Included_com_zxy_libjpegturbo_JpegTurboCompressor
#define _Included_com_zxy_libjpegturbo_JpegTurboCompressor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zxy_libjpegturbo_JpegTurboCompressor
 * Method:    nativeCompress
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zxy_libjpegturbo_JpegTurboCompressor_nativeCompress
  (JNIEnv *, jclass, jobject, jstring, jint, jboolean);

/*
 * Class:     com_zxy_libjpegturbo_JpegTurboCompressor
 * Method:    getLibjpegTurboVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zxy_libjpegturbo_JpegTurboCompressor_getLibjpegTurboVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_zxy_libjpegturbo_JpegTurboCompressor
 * Method:    getLibjpegVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zxy_libjpegturbo_JpegTurboCompressor_getLibjpegVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
